### ISSUE TITLE
CRAWLER NOT RUNNING

### ISSUE THREAD

**Issue by AlexanderPuckhaber** [gt-scheduler/crawler#4]
On GitHub Actions Panel:

`This scheduled workflow is disabled because there hasn't been activity in this repository for at least 60 days.`

Crawler hasn't run in 22 days and there have been a lot of section changes since then (and a lot during Phase 2)

**Comment by jazevedo620** [comment]
Wow that's some not-fun GitHub behavior.

Thanks a ton for flagging this; I went in a re-enabled it.

**Comment by jazevedo620** [comment]
Seems like now, while the actions *are* running, they aren't succeeding ([link, go to "Crawling" step](https://github.com/gt-scheduler/crawler/runs/3330413575?check_suite_focus=true)) =/

**Comment by jazevedo620** [comment]
From Discord:

> i'm taking a look at it
OSCAR is currently down, so that is probably it (crawler is stopping with ECONNRESET when accessing <https://oscar.gatech.edu/pls/bprod/bwckctlg.p_disp_dyn_ctlg>)
hopefully when OSCAR is back up it will work; in any case hard to debug when OSCAR is down

The action is succeeding now that Oscar is back up. Everything seems to be fine now; closing.
